library(tidyverse)
library(bayesAB)
library(pwr)

# https://www.statmethods.net/stats/power.html
#
# We will conduct a power test to determine the sample size required to detect a small differences (h=0.1)
# in conversion rate with 5% Type I error rate (sig.level=0.05) and 20% Type II error (power=1-TypeII=0.80).
power_test <- pwr.2p.test(h=0.1, 
                          sig.level=0.05, 
                          power=0.8)
# Grab the sample size generated by our power test.
n <- ceiling(power_test$n)
n

# Use the sample size calculation to generate some likely data for each webflow and our "prior knowledge" of the CTR for 
# webflow_a (ie, the current webflow) to define the population proportion for the sample webflow_a used in the test.
# Notice we have defined the true population proportions to be very close (since we are trying to pick up slight differences).
prior_knowledge_ctr <- 0.14
webflow_a = rbinom(n=n,
                   size=1,
                   prob=prior_knowledge_ctr)

webflow_b = rbinom(n=n,
                   size=1,
                   prob=0.16)

# Function to obtain some stats to be used in the hypothesis test and Bayes test
get_stats <- function(x) {
    conversions <-sum(x)
    sample_size <- length(x)
    conversion_rate <- round(conversions/sample_size, 4)
    variance <- conversion_rate*(1-conversion_rate)/sample_size
    lower_95 <- round(conversion_rate - 1.96*sqrt(variance), 4)
    upper_95 <- round(conversion_rate + 1.96*sqrt(variance), 4)
    my_stats <- list(conversions = conversions,
                     sample_size = sample_size,
                     conversion_rate = conversion_rate, 
                     variance = variance,
                     lower_95 = lower_95,
                     upper_95 = upper_95)
    return(my_stats)
}

webflow_a_stats <- get_stats(x=webflow_a)
webflow_a_stats

webflow_b_stats <- get_stats(x=webflow_b)
webflow_b_stats

# frequentist hypothesis test
# H0: webflow_a CTR == webflow_b CTR
# p > 0.05, so we fail to reject the null hypothesis 
prop.test(x = c(webflow_a_stats$conversions, webflow_b_stats$conversions), 
          n = c(webflow_a_stats$sample_size, webflow_b_stats$sample_size),
          conf.level = 0.95,
          alternative = 'two.sided')


# Instead of relying on a traditional hypothesis test...
#
# If we think about is_order as a vector of Bernoulli RV's, then we can use the beta distribution as the conjugate prior of p.  
#
# For clarity, we can imagine is_order as having been generated as follows,
#   webflow_a <- rbinom(n,1,p) 
# which implies that each,
#   webflow_a[i] ~ Bernoulli(p), 0 <= i <= n
#
# Scroll down to Details > Bernoulli
?bayesTest


# So, we need to find the (hyper)params that appropriately model p ~ Beta(alpha, beta).  To do so, we will 
# use our historical knowledge about p from the pretest A data. Specifically, we calculated the sample conversion 
# rate, aka the sample proportion p_hat, which estimates p, the population proportion, or true conversion probability.  
# 
#   p_hat = conversions / (conversions + drop_offs)
#         = 727 / (727 + 4274)
#         = 0.14 
#
#   95% CI: (0.1356, 0.1552)
#
# We also know the mean of the Beta distribution is given by,
#
#   E(p) = alpha / (alpha + beta)
#
# which looks very much like our defintion of p_hat.  So, we want p ~ Beta(alpha=727, beta=4274).
#
# We'll add the point estimate p_hat as well as the bounds of 95% CI for reference.

alpha <- prior_knowledge_ctr
beta <- webflow_a_stats$sample_size - prior_knowledge_ctr

plot_beta <- plotBeta(alpha=alpha, beta=beta)
plot_beta + 
    geom_vline(xintercept=pretest_A_stats$lower_95, linetype='dashed', color = 'darkblue') +
    geom_vline(xintercept=pretest_A_stats$upper_95, linetype='dashed', color = 'darkblue') +
    geom_vline(xintercept=pretest_A_stats$conversion_rate, linetype='solid', color = 'darkred') +
    xlim(0.1, 0.2) 

# This is our AB Test object    
abTest_1 <- bayesTest(session_level_test_webflow_A$is_order, 
                      session_level_test_webflow_B$is_order, 
                      priors = c('alpha' = alpha, 'beta' = beta), 
                      n_samples = 1e5, 
                      distribution = 'bernoulli')

# print yields summary statistics of the input data for conversion rates of pages A and B, 
# the parameters of chosen prior (our belief), and the number of posterior samples to draw 
# (1e5 is a good rule of thumb and should be large enough for the distribution to converge).
print(abTest_1)
# useful test results
summary(abTest_1)
# and vizualizations
plot(abTest_1)




